# -*- coding: utf-8 -*-
"""EJERCICIO CREATE TABLE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iOl8hI6o_g7FjyWtilAORThRUfyB5ci
"""

import sqlite3
import pandas as pd

# Conexión en memoria (se pierde al cerrar el notebook)
conn = sqlite3.connect(":memory:")
cur = conn.cursor() #objeto para ejecutar comandos de SQL

def query(sql, params=()):
    """Ejecuta un SELECT y devuelve un DataFrame para verlo bonito."""
    return pd.read_sql_query(sql, conn, params=params)

def run(sql, params=()):
    """Ejecuta INSERT/UPDATE/DELETE/DDL y hace commit."""
    cur.execute(sql, params)
    conn.commit()
    print("OK ->", sql.strip().splitlines()[0], "...")

"""##EJERCICIO 1
Una cadena de restaurantes necesita registrar en su base de datos el menú de platillos que ofrece. Crea una tabla llamada comida que cumpla con las siguientes especificaciones:
"""

cur.executescript ('''
DROP TABLE IF EXISTS comida;
CREATE TABLE comida(
    id_platillo INTEGER PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT(30),
    precio decimal (6,2) not null,
    disponible REAL);

    ''')
conn.commit()
print("Tablas creada correctamente")

# INSERT: alta de departamentos
run("""
insert into comida (id_platillo,nombre,categoria,precio,disponible) VALUES
(1,'HUEVOS CON JAMON','DESAYUNOS',55.90,TRUE),
(2,'COCTEL DE CAMARON','APERITIVOS',599,TRUE);""")

query("SELECT * FROM comida")

# UPDATE
run("UPDATE comida SET precio = precio * +100.10 WHERE disponible = TRUE")
query("SELECT * FROM comida")

# DELETE
run("DELETE FROM comida WHERE precio = '117.390';")
query("SELECT * FROM comida")

"""##EJERCICIO 2"""

Una escuela quiere registrar la información básica de sus alumnos.

cur.executescript ('''
DROP TABLE IF EXISTS alumnos;
CREATE TABLE alumnos(
id_Alumno INTEGER PRIMARY KEY autoincrement,
nombre varchar(50) not null,
grado varchar(10) not null,
edad int not null,
promedio decimal(4,2) not null
);

    ''')
conn.commit()
print("Tablas creada correctamente")

# INSERT: alta de alumnos
run("""INSERT INTO alumnos
(id_Alumno,nombre,grado,edad,promedio)
VALUES ('1','gael','4to','20','89.5'),
('2','hector','5to','85','20');""")

query("SELECT * FROM alumnos")

# UPDATE
run("""UPDATE alumnos
SET promedio = 'NA'
WHERE promedio <= 50;""")
query("SELECT * FROM alumnos")

# DELETE
run("DELETE FROM alumnos WHERE promedio = 'NA';")
query("SELECT * FROM alumnos")

"""##Ejercicio 3

La tiendita de la escuela necesita llevar el control de los productos que vende.
"""

cur.executescript ("""
DROP TABLE IF EXISTS productos;
create table productos(
id_producto INTEGER PRIMARY KEY autoincrement,
nombre varchar(50) not null,
tipo varchar (30) not null,
precio decimal (6,2) not null,
cantidad int not null
);

""")

conn.commit()
print("Tablas creada correctamente")

# INSERT: alta de productos
run("""INSERT INTO productos
(id_producto,nombre,tipo,precio,cantidad)
VALUES ('1','Jugo de Naranja','jugos','70','');""")
query("SELECT * FROM productos")

# UPDATE
run("""UPDATE productos
SET  precio = precio * 0.89
WHERE precio <= 70""")
query("SELECT * FROM productos")

# DELETE
run("DELETE FROM productos WHERE tipo = 'jugos';")
query("SELECT * FROM productos")